apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-springboot-app
  template:
    metadata:
      labels:
        app: kafka-springboot-app
    spec:
      containers:
      - name: kafka-container
        image: ashafqat/kafka-reader-app:v0.2
        volumeMounts:
        - name: client-cert
          mountPath: /data/p12     
        env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: BOOTSTRAP_SERVERS
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: GROUP_ID
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: TOPIC_NAME
        - name: TRUSTSTORE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: TRUSTSTORE_PASSWORD
        - name: TRUSTSTORE_LOCATION
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: TRUSTSTORE_LOCATION
        - name: TRUSTSTORE_TYPE
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: TRUSTSTORE_TYPE
      volumes:
      - name: client-cert
        secret:
          secretName: devops02-amq-internal-cert-key-pair