apiVersion: v1 
kind: ConfigMap
metadata:
  name: kafka-config
data:
  BOOTSTRAP_SERVERS: "your.kafka.broker:9092"
  GROUP_ID: "GROUP_ID"
  TOPIC_NAME: "TOPIC_NAME"
  TRUSTSTORE_PASSWORD: ""
  TRUSTSTORE_LOCATION: "/data/p12"
  TRUSTSTORE_TYPE: "PKCS12"