kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-config
  namespace: amq-instance
data:
  BOOTSTRAP_SERVERS: 'amq-devops02-instance-kafka-bootstrap.amq-devops02-instance.svc:9093'
  GROUP_ID: GROUP_ID
  TOPIC_NAME: topic1
  TRUSTSTORE_LOCATION: /data/crt/truststore.jks
  TRUSTSTORE_PASSWORD: mypassword
  TRUSTSTORE_TYPE: JKS

